### PR TITLE
 FIXED! Tags now REQUIRED + Optional text removed

### LINKED ISSUE #177: Put a minimum limit on the number of tags
Tags are helpful to know about the topics of the project at a glance. It should be made mandatory to add at least 3 tags while registration.

Overkill feature: add a button which fetches the tags from the github repo of the project.

### PR DESCRIPTION
**Pull request by ProgrammerSONGBIT**
Fixes #177

## Changes
- Added minimum 3 tags validation in `ProjectForm.tsx` before project submission.
- Validates that the tags field contains at least 3 non-empty, comma-separated tags when provided.
- Reuses a cleaned `tagsArray` both for validation and for sending tags to the backend.

## Testing
- Tested with 1 tag: shows "Minimum 3 tags required! (e.g: javascript, html, css)" and blocks submission. 
- Tested with 3+ tags (e.g. `javascript, html, css`): passes validation and proceeds to submit. 
## Details
This validation ensures project submissions have sufficient tags for better categorization and discoverability.
Updated form fields to require specific formats and added validation for tags.

### CODE REVIEW

**Comment by ProgrammerSONGBIT** [comment]
This is the changed PR for the issue #177 
This is the changed PR and this changed PR modifies the old PR, in this PR the fix tags are required and optional text is removed.

File: src/pages/ProjectForm.tsx [hunk 1]
```diff
@@ -82,29 +82,30 @@ function ProjectForm(props: { isEditing?: boolean }) {
...
+              required: "https://github.com/kossiitkgp/KWoC-Frontend",
               type: "url",
               placeholder: "https://github.com/kossiitkgp/KWoC-Frontend",
               defaultValue: isEditing ? projectInfo?.repo_link : undefined,
             },
             comm_channel: {
-              field: "Communication Channel",
+              field: "Communication Channel *",
               required: true,
               type: "url",
```
Comment (dipamsen) [inline src/pages/ProjectForm.tsx:93]: `required` should be a boolean

Additional `*` is not required, since it is annotated by the `required field.

File: src/pages/ProjectForm.tsx [hunk 2]
```diff
@@ -82,29 +82,30 @@ function ProjectForm(props: { isEditing?: boolean }) {
...
               placeholder: "https://github.com/kossiitkgp/KWoC-Frontend#readme",
               defaultValue: isEditing ? projectInfo?.readme_link : undefined,
             },
             tags: {
-              field: "Tags (Optional)",
+              field: "Tags * (e.g: javascript, html, css)",
+              required: true,
               type: "text",
-              placeholder: "javascript,html,css",
+              placeholder: "javascript, html, css",
```
Comment (dipamsen) [inline src/pages/ProjectForm.tsx:108]: Same here, `*` is not required, also `(e.g.` is unnecessary.

**Comment by ProgrammerSONGBIT** [comment]
All fixes applied! 

1.  `required: true` (boolean everywhere)
2.  Removed all extra `*` markings  
3.  `Tags` (clean field name + placeholder)

**Comment by dipamsen** [comment]
Thanks again for your contribution, merging! :rocket:
